import type { WorkItem } from './works'

// コードで管理する実績。管理画面（Blob）の実績より前に表示され、管理画面からは編集・削除できない。
// 管理画面の「通常の投稿に取り込む」で Blob に移すと、同じ id の項目はこちらからは表示されなくなる。
export const CODE_MANAGED_WORKS: WorkItem[] = [
  {
    id: 'duovc',
    title: 'マッチングサービス DuoVC',
    category: 'アプリ開発',
    description: '設定ファイルの差し替えだけで別ジャンルのマッチングサービスを立ち上げられる汎用基盤を開発し、その上でDuoVCを構築・公開しました。',
    period: '2026/07',
    location: 'オンライン',
    scale: 'Webサービス / 汎用基盤',
    tags: ['マッチング', 'Next.js', 'プラットフォーム'],
    managedInCode: true,
  },
  {
    id: 'toybox',
    title: 'Toybox クリエイター投稿プラットフォーム',
    category: 'アプリ開発',
    description: 'eスポーツ・イベント・デザイン・Web運用のクリエイターが、プロダクトや実績・ノウハウを投稿して共有できるプラットフォームを開発・運営しています。',
    period: '2026/05〜',
    location: 'オンライン',
    scale: 'Webサービス / 自社運営',
    tags: ['プラットフォーム', 'Next.js', '自社サービス'],
    managedInCode: true,
  },
  {
    id: 'smash-note',
    title: 'スマノート（スマブラ対戦ノート）',
    category: 'アプリ開発',
    description: '対戦後の負け筋を記録して振り返れるスマブラ向けの対戦ノート。フレームデータを同梱し、練習の優先順位を決めやすくしました。',
    period: '2026/09',
    location: 'オンライン',
    scale: 'Webアプリ',
    tags: ['eスポーツ', 'スマブラ', 'Webアプリ'],
    managedInCode: true,
  },
  {
    id: 'tools-seo',
    title: 'ミニ計算ツールサイト「サッと計算」',
    category: 'アプリ開発',
    description: '検索需要のある計算ツールを毎日1本ずつ追加していく実用サイト。企画から公開までを自動化して運用しています。',
    period: '2026/07〜',
    location: 'オンライン',
    scale: 'ツールサイト / 毎日更新',
    tags: ['SEO', 'ツール', '自動化'],
    managedInCode: true,
  },
  {
    id: 'web-tenjijo',
    title: 'Web展示場 WEB MIHONICHI',
    category: 'Web制作',
    description: '業種別のWebサイトデザイン見本を並べて比較できるギャラリーサイト。毎日新しい見本を追加しています。',
    period: '2026/10〜',
    location: 'オンライン',
    scale: 'ギャラリーサイト / 毎日更新',
    tags: ['デザイン見本', 'ギャラリー', '自動化'],
    managedInCode: true,
  },
  {
    id: 'daily-topics',
    title: 'AI・金融トピック日報サイト',
    category: 'アプリ開発',
    description: 'AIと金融のニュースを毎朝自動で収集・要約して公開する2つの日報サイトを開発・運用しています。',
    period: '2026/06〜',
    location: 'オンライン',
    scale: '2サイト / 毎朝自動更新',
    tags: ['自動化', 'ニュース', 'AI'],
    managedInCode: true,
  },
  {
    id: 'eitango',
    title: '英単語学習ゲーム「えいたん」',
    category: 'アプリ開発',
    description: 'ストーリーつきのステージ制で英単語を覚えられる学習ゲームを開発しました。',
    period: '2026/07',
    location: 'オンライン',
    scale: 'Webゲーム',
    tags: ['教育', 'ゲーム', 'Webアプリ'],
    managedInCode: true,
  },
  {
    id: 'resuba-arena',
    title: '論戦対戦ゲーム「レスバアリーナ」',
    category: 'アプリ開発',
    description: '匿名で1対1の論戦を行い、AIが勝敗を判定してレートが変動する対戦ゲーム。マッチング・AI審判・Eloレートを実装しました。',
    period: '2026/07',
    location: 'オンライン',
    scale: 'Webゲーム / リアルタイム対戦',
    tags: ['AI', '対戦', 'ゲーム'],
    managedInCode: true,
  },
  {
    id: 'oyasumi-story',
    title: '読み聞かせ配信サービス「おやすみ物語」',
    category: 'アプリ開発',
    description: 'お子さまを主人公にした読み聞かせのお話を毎晩LINEで届ける月額サービスを開発しました。',
    period: '2026/06',
    location: 'オンライン',
    scale: 'サブスクリプション / LINE連携',
    tags: ['LINE', 'サブスク', 'AI'],
    managedInCode: true,
  },
  {
    id: 'ai-chokyo-diary',
    title: 'AI調教日記',
    category: 'アプリ開発',
    description: 'AIの育て方やプロンプトを記事で公開し、有料記事をクリエイターごとの月額課金で販売できるメディアを開発しました。',
    period: '2026/06',
    location: 'オンライン',
    scale: 'メディア / Stripe決済',
    tags: ['メディア', '決済', 'AI'],
    managedInCode: true,
  },
  {
    id: 'line-manager',
    title: '公式LINE管理アプリ',
    category: 'アプリ開発',
    description: '公式LINEへの問い合わせにAIが返信の下書きを作り、担当者が承認して送信できる管理アプリ。友だち管理も備えています。',
    period: '2026/06',
    location: 'オンライン',
    scale: '業務アプリ',
    tags: ['LINE', 'AI', '業務効率化'],
    managedInCode: true,
  },
  {
    id: 'youtube-shorts',
    title: 'YouTube 雑学ショートの自動制作・運用',
    category: '動画制作',
    description: '台本・音声・映像・サムネイル・投稿までを自動化した雑学ショートチャンネルを毎日運用しています。',
    period: '2026/06〜',
    location: 'YouTube',
    scale: '毎日投稿',
    tags: ['YouTube', 'ショート', '自動化'],
    managedInCode: true,
  },
  {
    id: 'youtube-kaisetsu',
    title: 'YouTube 図解解説動画の自動制作',
    category: '動画制作',
    description: '図解つきの10分前後の解説動画を、構成から編集まで自動で制作しています。',
    period: '2026/09〜',
    location: 'YouTube',
    scale: '長尺動画',
    tags: ['YouTube', '解説動画', '自動化'],
    managedInCode: true,
  },
  {
    id: 'youtube-bgm-sleep',
    title: '作業用BGM・睡眠用朗読チャンネル運用',
    category: '動画制作',
    description: '音源から映像まで自前で作る60分の作業用BGMと、90分の睡眠用朗読をそれぞれ毎日投稿しています。',
    period: '2026/07〜',
    location: 'YouTube',
    scale: '2チャンネル / 毎日投稿',
    tags: ['YouTube', 'BGM', '朗読'],
    managedInCode: true,
  },
]

// Blob にまだ取り込まれていないコード管理の実績
export function codeManagedWorksNotIn(works: WorkItem[]): WorkItem[] {
  const storedIds = new Set(works.map((w) => w.id))
  return CODE_MANAGED_WORKS.filter((w) => !storedIds.has(w.id))
}
