import type { WorkItem } from './works'

// コードで管理する実績。管理画面（Blob）の実績より前に表示され、管理画面からは編集・削除できない。
// 管理画面の「通常の投稿に取り込む」で Blob に移すと、同じ id の項目はこちらからは表示されなくなる。
export const CODE_MANAGED_WORKS: WorkItem[] = [
  // お客様の案件（店名・個人名の掲載はご本人の了承済み）
  {
    id: 'cafe-meo-llmo',
    title: 'CAFE MANO様 Googleマップ・検索での集客支援',
    category: 'MEO・LLMO対策',
    description:
      '和泉市で18年続くカフェの、Googleマップと検索での見つけやすさを支援しています。グルメサイトや地図アプリの登録情報の誤りを洗い出して直し、Googleビジネスプロフィールの更新を続けています。2026年5〜9月のプロフィールからの反応（ルート検索・電話・メニュー閲覧・サイトへのアクセス）は前年同期比+50.7%、ルート検索は+75.6%でした。',
    period: '2026/04〜',
    location: '大阪府和泉市',
    scale: '反応数 前年同期比+50.7%（2026年5〜9月）',
    tags: ['MEO', 'LLMO', 'Googleビジネスプロフィール'],
    managedInCode: true,
  },
  {
    id: 'acupuncture-clinic-site',
    title: '鍼灸マッサージ院モーヴ様 公式サイト制作',
    category: 'Web制作',
    description: '鍼灸マッサージ院の公式サイトを制作し、あわせてGoogleビジネスプロフィールの登録情報を整えました。',
    period: '2026/05',
    location: '大阪府和泉市',
    scale: '公式サイト / Googleビジネスプロフィールの整備',
    tags: ['Webサイト制作', 'MEO', '治療院'],
    managedInCode: true,
  },
  {
    id: 'apparel-agency-site',
    title: 'Hu-Mam（中山千佳様）公式サイト制作',
    category: 'Web制作',
    description:
      'アパレル店舗の販売代行を営む個人事業主さまの公式サイトを制作しました。同業11社のサイトを比べたうえで、女性代表がみずから店舗スタッフを管理している点が伝わる構成にしています。',
    period: '2026/04',
    location: '大阪府',
    scale: '5ページ構成',
    tags: ['Webサイト制作', 'コーポレートサイト', '競合調査'],
    imageUrl: '/works/hu-mam.jpg',
    managedInCode: true,
  },
  // 自社で開発・運営しているサービスと動画
  {
    id: 'duovc',
    title: 'マッチングサービス DuoVC',
    category: 'アプリ開発',
    description: '設定ファイルの差し替えだけで別ジャンルのマッチングサービスを立ち上げられる汎用基盤を開発し、その上でDuoVCを構築・公開しました。',
    period: '2026/07',
    location: 'オンライン',
    scale: 'Webサービス / 汎用基盤',
    tags: ['マッチング', 'Next.js', 'プラットフォーム'],
    imageUrl: '/works/duovc.jpg',
    managedInCode: true,
  },
  {
    id: 'toybox',
    title: 'Toybox クリエイター投稿プラットフォーム',
    category: 'アプリ開発',
    description: 'eスポーツ・イベント・デザイン・Web運用のクリエイターが、プロダクトや実績・ノウハウを投稿して共有できるプラットフォームを開発・運営しています。',
    period: '2026/05〜',
    location: 'オンライン',
    scale: 'Webサービス / 自社運営',
    tags: ['プラットフォーム', 'Next.js', '自社サービス'],
    imageUrl: '/works/toybox.jpg',
    managedInCode: true,
  },
  {
    id: 'smash-note',
    title: 'スマノート（スマブラ対戦ノート）',
    category: 'アプリ開発',
    description: '対戦後の負け筋を記録して振り返れるスマブラ向けの対戦ノート。フレームデータを同梱し、練習の優先順位を決めやすくしました。',
    period: '2026/09',
    location: 'オンライン',
    scale: 'Webアプリ',
    tags: ['eスポーツ', 'スマブラ', 'Webアプリ'],
    imageUrl: '/works/smash-note.jpg',
    managedInCode: true,
  },
  {
    id: 'tools-seo',
    title: 'ミニ計算ツールサイト「サッと計算」',
    category: 'アプリ開発',
    description: '検索需要のある計算ツールを毎日1本ずつ追加していく実用サイト。企画から公開までを自動化して運用しています。',
    period: '2026/07〜',
    location: 'オンライン',
    scale: 'ツールサイト / 毎日更新',
    tags: ['SEO', 'ツール', '自動化'],
    imageUrl: '/works/tools-seo.jpg',
    managedInCode: true,
  },
  {
    id: 'web-tenjijo',
    title: 'Web展示場 WEB MIHONICHI',
    category: 'Web制作',
    description: '業種別のWebサイトデザイン見本を並べて比較できるギャラリーサイト。毎日新しい見本を追加しています。',
    period: '2026/10〜',
    location: 'オンライン',
    scale: 'ギャラリーサイト / 毎日更新',
    tags: ['デザイン見本', 'ギャラリー', '自動化'],
    managedInCode: true,
  },
  {
    id: 'daily-topics',
    title: 'トピック日報サイト（AI・金融）',
    category: 'アプリ開発',
    description: 'AIと金融のニュースを毎朝自動で収集・要約して公開する2つの日報サイトを開発・運用しています。',
    period: '2026/06〜',
    location: 'オンライン',
    scale: '2サイト / 毎朝自動更新',
    tags: ['自動化', 'ニュース'],
    imageUrl: '/works/daily-topics.jpg',
    managedInCode: true,
  },
  {
    id: 'eitango',
    title: '英単語学習ゲーム「えいたん」',
    category: 'アプリ開発',
    description: 'ストーリーつきのステージ制で英単語を覚えられる学習ゲームを開発しました。',
    period: '2026/07',
    location: 'オンライン',
    scale: 'Webゲーム',
    tags: ['教育', 'ゲーム', 'Webアプリ'],
    imageUrl: '/works/eitango.jpg',
    managedInCode: true,
  },
  {
    id: 'resuba-arena',
    title: '論戦対戦ゲーム「レスバアリーナ」',
    category: 'アプリ開発',
    description: '匿名で1対1の論戦を行い、AIが勝敗を判定してレートが変動する対戦ゲーム。マッチング・AI審判・Eloレートを実装しました。',
    period: '2026/07',
    location: 'オンライン',
    scale: 'Webゲーム / リアルタイム対戦',
    tags: ['対戦', 'ゲーム', 'レート'],
    imageUrl: '/works/resuba-arena.jpg',
    managedInCode: true,
  },
  {
    id: 'oyasumi-story',
    title: '読み聞かせ配信サービス「おやすみ物語」',
    category: 'アプリ開発',
    description: 'お子さまを主人公にした読み聞かせのお話を毎晩LINEで届ける月額サービスを開発しました。',
    period: '2026/06',
    location: 'オンライン',
    scale: 'サブスクリプション / LINE連携',
    tags: ['LINE', 'サブスク'],
    imageUrl: '/works/oyasumi-story.jpg',
    managedInCode: true,
  },
  {
    id: 'youtube-shorts',
    title: 'YouTube 雑学ショートの自動制作・運用',
    category: '動画制作',
    description: '台本・音声・映像・サムネイル・投稿までを自動化した雑学ショートチャンネルを毎日運用しています。',
    period: '2026/06〜',
    location: 'YouTube',
    scale: '毎日投稿',
    tags: ['YouTube', 'ショート', '自動化'],
    managedInCode: true,
  },
  {
    id: 'youtube-kaisetsu',
    title: 'YouTube 図解解説動画の自動制作',
    category: '動画制作',
    description: '図解つきの10分前後の解説動画を、構成から編集まで自動で制作しています。',
    period: '2026/09〜',
    location: 'YouTube',
    scale: '長尺動画',
    tags: ['YouTube', '解説動画', '自動化'],
    managedInCode: true,
  },
  {
    id: 'youtube-bgm-sleep',
    title: '作業用BGM・睡眠用朗読チャンネル運用',
    category: '動画制作',
    description: '音源から映像まで自前で作る60分の作業用BGMと、90分の睡眠用朗読をそれぞれ毎日投稿しています。',
    period: '2026/07〜',
    location: 'YouTube',
    scale: '2チャンネル / 毎日投稿',
    tags: ['YouTube', 'BGM', '朗読'],
    managedInCode: true,
  },
  // 代表個人の活動（大会名・研修先の名前は出さない。大会の写真は大会名が映らない範囲で切り出したもの）
  {
    id: 'local-esports-tournament',
    title: '地域のeスポーツ大会の企画・運営',
    category: '大会運営',
    description:
      '代表が個人で主催し、2023年から毎月続けている地域のeスポーツ大会です。1回あたり20〜100名ほどが参加しています。企画、当日の運営、告知用のデザイン、SNSでの告知までを一人で担当しています。',
    period: '2023/03〜',
    location: '大阪府和泉市',
    scale: '毎月開催 / 1回20〜100名',
    tags: ['eスポーツ', '大会運営', 'SNS告知'],
    imageUrl: '/works/event-venue.jpg',
    managedInCode: true,
  },
  {
    id: 'tournament-promo-design',
    title: 'eスポーツ大会の告知フライヤー・紹介サイト制作',
    category: 'デザイン',
    description: '主催しているeスポーツ大会の告知フライヤーと、自治体や協賛企業に向けた紹介サイトを制作しました。',
    period: '2026',
    location: '-',
    scale: 'フライヤー / 紹介サイト',
    tags: ['フライヤー', 'Webサイト制作', 'eスポーツ'],
    managedInCode: true,
  },
  {
    id: 'genai-training',
    title: '企業向け 生成AIの業務活用研修の講師',
    category: '研修・セミナー',
    description:
      '企業の社員の方に向けて、文書作成や要約などの業務で生成AIを使う方法を学ぶ研修を企画し、資料づくりと講師を担当しています。',
    period: '2026/07〜',
    location: '企業研修',
    scale: '90分',
    tags: ['研修', '講師', '業務効率化'],
    managedInCode: true,
  },
  {
    id: 'sns-strategy-seminar',
    title: '製造業・BtoB企業向け SNS運用セミナーの講師',
    category: '研修・セミナー',
    description:
      '製造業・BtoB企業の方に向けて、経営の目標からSNSの目的と数値目標を決め、運用して見直すまでの流れを学ぶセミナーを企画し、資料づくりと講師を担当しています。',
    period: '2026/07〜',
    location: '企業研修',
    scale: '90分 / ワーク2本',
    tags: ['SNS運用', 'セミナー', '講師'],
    managedInCode: true,
  },
]

// Blob にまだ取り込まれていないコード管理の実績
export function codeManagedWorksNotIn(works: WorkItem[]): WorkItem[] {
  const storedIds = new Set(works.map((w) => w.id))
  return CODE_MANAGED_WORKS.filter((w) => !storedIds.has(w.id))
}
